deploy:
  provider: pypi
  user: sadok
  password:
    secure: C/zy1RqScctbuEb62eF3KxUYllkGOcF1rrFHVk+lbNFFd8swCI6meQi/o3bAzDgiVCe3fnpEUet8C5ESJ7AqscjLStri+Xj5NOSmXlY4bi+4Q0w2PHUh2wksdfA22YfN82iuTXQWmYRC56FietBwAZTtncHUqWEb97ca47RNqWQeejAzblMDp2XOs/9LoDvxXs2LZ/hqcHPQ8+xwDI1h4gtjckNqFZZEJBAxMy5t1BftsFyIf15FUnNxDaLMH4Uj38gKRuk65WFiHnv4+i2NCBtYDokVTCFZGudmg4d4XZt/6SFggkGKMIXDfKnIb0RzUQGdJ2nRC9OXpNh+0BRnGOfn//hoLK3+J4bdF88LW5XROLfnrI5TZ3K8AccmAtREHp9kZb06VN4mvFOb96X8p8MiOMkosntVF8XMEzPDTLp4MbdkFZBG/fdnm2FsH2N/Oc/wKS7QN5SrA77faC86cRp5G/O7WZS+Y3edOMj4vTzGanU9UT6sdVGEHrs68zDSYs1Cf3jrPJsTE5z/6tz8SGj96I9zQ/RtouI0RILAdl5TIr7Kt1ru7RJlKNgmc0w1F0rBFTtErT+N5yxbGIy8HZ6B1jwM6jt+Omquimk/hGA9yob5T4CIaJpWK50OVSnlxHpt9t8d5akh4YtdKS27DEJxaxCHhzxrgV7s8quXRg0=
  on:
    condition: $TOXENV == py27
    tags: true
    distributions: sdist bdist_wheel
    repo: hugombarreto/remotestatsclient
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=pypy
install: pip install -U tox
language: python
python: 3.5
script: tox
